import 'package:flutter/material.dart';
import '../features/learning/class_detail_screen.dart' show ContentType;

class ClassRepository {
  static final List<Map<String, dynamic>> classes = [
    {
      'id': 1,
      'title': 'Desain Antarmuka & Pengalaman Pengguna',
      'code': 'D4SM-42-03',
      'instructor': 'Ady',
      'progress': 0.6,
      'color': Colors.red,
      'materi': [
        {
          'id': '1',
          'badgeText': 'Pertemuan 1',
          'badgeColor': Colors.blue,
          'title': '01 - Pengantar User Interface Design',
          'description': '3 URLs, 2 Files, 3 Interactive Content',
          'isCompleted': true,
          'contentType': ContentType.lesson,
          'type': 'ui_design',
        },
        {
          'id': '2',
          'badgeText': 'Pertemuan 2',
          'badgeColor': Colors.blue,
          'title': '02 - User Experience',
          'description': '2 URLs, 1 Files',
          'isCompleted': true,
          'contentType': ContentType.lesson,
          'type': 'ui_design',
        },
        {
          'id': '3',
          'badgeText': 'Pertemuan 3',
          'badgeColor': Colors.blue,
          'title': '03 - Prototyping',
          'description': '4 URLs, 1 Files',
          'isCompleted': false,
          'contentType': ContentType.lesson,
          'type': 'ui_design',
        },
      ],
    },
    {
      'id': 2,
      'title': 'Mobile Programming',
      'code': 'MB-20-01',
      'instructor': 'Haikal',
      'progress': 0.3,
      'color': Colors.blue,
      'materi': [
        {
          'id': 'm1',
          'badgeText': 'Pertemuan 1',
          'badgeColor': Colors.orange,
          'title': '01 - Pengantar Flutter',
          'description': 'Video & Modul',
          'isCompleted': true,
          'contentType': ContentType.lesson,
          'type': 'mobile_programming',
        },
        {
          'id': 'm2',
          'badgeText': 'Pertemuan 2',
          'badgeColor': Colors.orange,
          'title': '02 - Dasar Mobile Programming',
          'description': 'Source Code & Quiz',
          'isCompleted': false,
          'contentType': ContentType.lesson,
          'type': 'mobile_programming',
        },
      ],
    },
    {
      'id': 3,
      'title': 'Web Programming',
      'code': 'WB-20-02',
      'instructor': 'Budi',
      'progress': 0.0,
      'color': Colors.purple,
      'materi': [
        {
          'id': 'w1',
          'badgeText': 'Pertemuan 1',
          'badgeColor': Colors.purple,
          'title': '01 - Pengantar Web Development',
          'description': 'HTML & CSS Basics',
          'isCompleted': true,
          'contentType': ContentType.lesson,
          'type': 'web_programming',
        },
        {
          'id': 'w2',
          'badgeText': 'Pertemuan 2',
          'badgeColor': Colors.purple,
          'title': '02 - JavaScript Fundamentals',
          'description': 'Interactive Logic',
          'isCompleted': false,
          'contentType': ContentType.lesson,
          'type': 'web_programming',
        },
      ],
    },
  ];
}
